# -*- mode: ruby -*-
# vi: set ft=ruby :
#
Vagrant.configure(2) do |config|
    config.vm.define 'debian94' do |debian|
        debian.vm.box = 'chriswayg/debian-9.4.0-x86_64'
        debian.vm.synced_folder '.', '/vagrant', disabled: false
        debian.vm.provider 'virtualbox' do |vb|
            vb.name = 'debian94'
            vb.cpus = 1
            vb.memory = 1024
        end
    end
end
